### PR TITLE
Here are some edits that I'm suggesting.

### PR DESCRIPTION
**Pull request by non**
The main changes I made:

 1. I tried to flesh out the Logarithm example a bit.
 2. I removed unapply (which I think was misleading)
 3. I added some code addressing implicit enrichment.
 4. A bit of general clean up.

As far as my thoughts on the proposal:

 1. Even if there's no precedent for removing .asInstanceOf calls, I'd
    really prefer to completely erase those differences at
    compile-time if possible. I don't see a strong reason not to do
    this, and I'd like the encoding to resemble hand-written code when
    possible.

 2. I'm still somewhat bummed out about having to use implicit
    enrichment for value classes. I still think the proposal has a lot
    of merit, but I'd feel a bit better if we knew that enrichments
    were going directly to static methods, rather than relying on the
    complex machinery of value classes. That said, I still haven't
    benchmarked things, so it may be fine, but there's just a lot of
    machinery there that can be hard to reason about.

 3. I really like the in-companion / out-of-companion distinction for
    when opaque types become transparent. I think it should be easy
    for people to choose their level of opaqueness (i.e. people
    can choose when and how values can be lifted/lowered).

 4. I wonder if it would be useful to talk about how people could
    choose to define things like (Logarithm =:= Double) and/or (Double
    =:= Logarithm) if desired? I don't see any reason it wouldn't be
    possible to put these in implicit scope, but I haven't thought it
    through yet.

 5. Related to (4), we should ensure that conversions between the
    opaque type and the underlying type are always free. Consider:

      opaque type X = Int

      object X {
        def subst[F[_]](value: F[Int]): F[X] = value
      }

    In situations like tagging, the user will often want to be able to
    tag a very complex structure without having to reallocate, iterate
    over, inspect, or do anything. I want to be sure we can support
    constructions like this.

 6. I think we should drop multi-value opaque types. I don't like the
    idea of special-casing tuples, and there really isn't any other
    good syntax I can think of for them. The multi-value proposal
    really leaned more heavily on having built-in static extension
    methods, which the current proposal doesn't. They were always a
    bit of a long-shot due to their similarity with the existing value
    classes (as far as auto-boxing/unboxing, bridge methods, etc.)

Thanks for working on this! I'm sorry I'm leaving this so late, there
are likely further improvements we could make but I don't see them
now. I do feel like things are relatively well-scoped as-is.

### CODE REVIEW

**Comment by non** [comment]
This is an interesting direction that someone could choose to take opaque types. I don't see an obvious reason why something like this shouldn't be allowed. What do you think?

```scala
package object example {

  opaque type Tag[S, T] = S

  object Tag {
    def tag[S, T](s: S): Tag[S, T] = s
    def untag[S, T](st: Tag[S, T]): S = st

    def tags[F[_], S, T](fs: F[S]): F[Tag[S, T]] = fs
    def untags[F[_], S, T](fs: F[Tag[S, T]]): F[S] = fs

    implicit class UntagOps[S, T](st: Tag[S, T]) extends AnyVal {
      def untag: S = st
    }

    implicit class UntagsOps[F[_], S, T](fs: F[Tag[S, T]]) extends AnyVal {
      def untags: F[S] = fs
    }
  }

  type @@[S, T] = Tag[S, T]

  implicit class TagOps[S](s: S) extends AnyVal {
    def tag[T]: S @@ T = Tag.tag(s)
  }

  implicit class TagsOps[F[_], S](fs: F[S]) extends AnyVal {
    def tags[T]: F[S @@ T] = Tag.tags(fs)
  }

  trait Meter
  trait Foot
  trait Fathom

  val x: Double @@ Meter = (1e7).tag[Meter]
  val xs: Array[Double @@ Meter] = Array(1.0, 2.0, 3.0).tags[Meter]
  val o: Ordering[Double @@ Meter] = implicitly[Ordering[Double]].tags[Meter]

  val y: Double @@ Foot = (123.0).tag[Foot]

  o.compare(x, x) // 0
  o.compare(x, y) // does not compile
}
```

One advantage of letting opaque types include phantom types (and generic types) is that it means that someone who wants to use many different tags doesn't have to write duplicative boilerplate for each one. For example, in a "tagging" situation, methods like `tag`, `stag`, and so on will probably be wanted in all cases (and I don't see an obvious way to have many opaque types share implementations via a trait that their companions all extend).

**Comment by jvican** [comment]
Good changes @non. Merging and I'll reply to all your enquiries/observations in a follow-up PR.

**Comment by jvican** [comment]
I reply here inline.

>  1. Even if there's no precedent for removing .asInstanceOf calls, I'd
    really prefer to completely erase those differences at
    compile-time if possible. I don't see a strong reason not to do
    this, and I'd like the encoding to resemble hand-written code when
    possible.

I agree this is desirable. I'll add our preference to the document. However, note that this may have no effect on performance if the JVM runtime is effectively removing the cast because of CHA.
  
> I'm still somewhat bummed out about having to use implicit
enrichment for value classes. I still think the proposal has a lot
of merit, but I'd feel a bit better if we knew that enrichments
were going directly to static methods, rather than relying on the
complex machinery of value classes. That said, I still haven't
benchmarked things, so it may be fine, but there's just a lot of
machinery there that can be hard to reason about.
  
We'll probably need to benchmark this and see if there's a difference. I completely agree that is performance sensitive... In theory, I don't see any reason why we shouldn't make the synthetic extension methods created by value classes static when the static SIP implementation is done.
  
This is the current desugaring for an implicit class over a `String` with a method `show`:
```scala
  <synthetic> object iw$A extends Object {
    final def show$extension($this: String): Unit = scala.Predef.println($this);
    final <synthetic> def hashCode$extension($this: String): Int = $this.hashCode();
    final <synthetic> def equals$extension($this: String, x$1: Object): Boolean
    ...
}
```
  
If we make `show$extension` et al static, we can probably recover from a hypothetical hit on performance. The benefit of this approach is that it would improve also the status quo for normal value classes.
  
I'll add this to the technical discussions.

>  3. I really like the in-companion / out-of-companion distinction for
    when opaque types become transparent. I think it should be easy
    for people to choose their level of opaqueness (i.e. people
    can choose when and how values can be lifted/lowered).
  
Me too, I think it is elegant.
  
>  4. I wonder if it would be useful to talk about how people could
    choose to define things like (Logarithm =:= Double) and/or (Double
    =:= Logarithm) if desired? I don't see any reason it wouldn't be
    possible to put these in implicit scope, but I haven't thought it
    through yet.
  
Wouldn't it be possible to add these proofs in the type companion? The idea would be that with these in the scope, the Scala compiler will not generate the synthetic implicit defs.
  
>  5. Related to (4), we should ensure that conversions between the
    opaque type and the underlying type are always free. Consider:

      opaque type X = Int

      object X {
        def subst[F[_]](value: F[Int]): F[X] = value
      }
  
I agree. I think the proposal specifies this requirement implicitly, I'll make it more explicit. The neat thing is that having most of the type alias functionality already gives us this "free tagging". If we remove at compile-time the `asInstanceOf` checks, we will have the certainty that this is the case, too.
  
> I think we should drop multi-value opaque types. I don't like the
idea of special-casing tuples, and there really isn't any other
good syntax I can think of for them. The multi-value proposal
really leaned more heavily on having built-in static extension
methods, which the current proposal doesn't. They were always a
bit of a long-shot due to their similarity with the existing value
classes (as far as auto-boxing/unboxing, bridge methods, etc.)
  
Agreed. Note my comments on the future of static extension methods above. But I think it's better to remove it and we can revisit it in the future.

**Comment by jvican** [comment]
Hey @non | @erik-stripe, my last commit adds these discussions to the document. https://github.com/non/scala.github.com/commit/fb85c80c6f276095e7f867bdaf1fcc65967102af

**Pull request merged**
